window.KS2_SENTENCE_BANK = Object.assign(window.KS2_SENTENCE_BANK || {}, {
  experiment: [
    "We will experiment with different seeds in the school garden.",
    "The class planned an experiment to test how ice melts.",
    "Mia recorded every result after the experiment.",
    "Our science experiment used water, salt, and paper.",
    "The experiment showed that warm air rises.",
    "Before the experiment, the teacher checked the safety rules.",
    "Each group wrote a prediction for the experiment.",
    "The experiment helped us learn about magnets.",
    "After the experiment, we cleaned the desks carefully.",
    "Ben enjoyed the experiment because it was hands-on.",
    "The teacher wrote the word experiment on the board.",
    "We saw the word experiment on a flashcard.",
    "I heard the word experiment in the dictation.",
    "Our group used the word experiment in a story.",
    "Please spell the word experiment carefully.",
    "Sam said the word experiment aloud to the class.",
    "We checked the spelling of experiment against the answer sheet.",
    "The quiz included the word experiment as a challenge.",
    "I remembered the word experiment after more practice.",
    "The card showed the word experiment in bold."
  ],
  extreme: [
    "The extreme cold made the pond freeze overnight.",
    "The extreme heat pushed us to sit in the shade.",
    "The class talked about extreme weather in geography.",
    "She used extreme care when carrying the glass jar.",
    "The storm caused extreme waves on the coast.",
    "Dad checked the road during extreme fog.",
    "The walk felt extreme because the hill was so steep.",
    "The mountain pass had extreme weather in winter.",
    "The runners slowed down in extreme heat.",
    "We needed coats because the extreme wind was biting.",
    "The teacher wrote the word extreme on the board.",
    "We saw the word extreme on a flashcard.",
    "I heard the word extreme in the dictation.",
    "Our group used the word extreme in a story.",
    "Please spell the word extreme carefully.",
    "Sam said the word extreme aloud to the class.",
    "We checked the spelling of extreme against the answer sheet.",
    "The quiz included the word extreme as a challenge.",
    "I remembered the word extreme after more practice.",
    "The card showed the word extreme in bold."
  ],
  famous: [
    "The museum is famous for its dinosaur bones.",
    "The town is famous for its old bridge.",
    "Our class read about a famous explorer.",
    "The singer became famous after the concert.",
    "The castle is famous with visitors from many countries.",
    "That footballer is famous across the world.",
    "The school choir sang a song by a famous composer.",
    "The park is famous for its bright spring flowers.",
    "We saw a famous painting on the trip.",
    "The lighthouse is famous in our county.",
    "The teacher wrote the word famous on the board.",
    "We saw the word famous on a flashcard.",
    "I heard the word famous in the dictation.",
    "Our group used the word famous in a story.",
    "Please spell the word famous carefully.",
    "Sam said the word famous aloud to the class.",
    "We checked the spelling of famous against the answer sheet.",
    "The quiz included the word famous as a challenge.",
    "I remembered the word famous after more practice.",
    "The card showed the word famous in bold."
  ],
  favourite: [
    "My favourite book is on the shelf.",
    "Jam is my favourite topping on toast.",
    "Ben chose his favourite seat by the window.",
    "Sunday is my favourite day of the week.",
    "That blue jumper is her favourite one.",
    "Our favourite game is hide and seek.",
    "The teacher asked for our favourite story.",
    "Pizza is my favourite dinner on Fridays.",
    "We visited my favourite park after school.",
    "Her favourite song played at the party.",
    "The teacher wrote the word favourite on the board.",
    "We saw the word favourite on a flashcard.",
    "I heard the word favourite in the dictation.",
    "Our group used the word favourite in a story.",
    "Please spell the word favourite carefully.",
    "Sam said the word favourite aloud to the class.",
    "We checked the spelling of favourite against the answer sheet.",
    "The quiz included the word favourite as a challenge.",
    "I remembered the word favourite after more practice.",
    "The card showed the word favourite in bold."
  ],
  february: [
    "February is a short month.",
    "In February, we saw snow on the hill.",
    "My birthday is in February.",
    "The school trip is planned for February.",
    "February often brings cold mornings.",
    "We made cards for February half term.",
    "Mum checked the calendar for February.",
    "Our class project starts in February.",
    "February was busy for the football team.",
    "The last day of February arrived quickly.",
    "The teacher wrote the word february on the board.",
    "We saw the word february on a flashcard.",
    "I heard the word february in the dictation.",
    "Our group used the word february in a story.",
    "Please spell the word february carefully.",
    "Sam said the word february aloud to the class.",
    "We checked the spelling of february against the answer sheet.",
    "The quiz included the word february as a challenge.",
    "I remembered the word february after more practice.",
    "The card showed the word february in bold."
  ],
  forward: [
    "Step forward when your name is called.",
    "The team moved forward after the break.",
    "She leaned forward to hear the answer.",
    "Keep the bike moving forward on the path.",
    "Ben ran forward to catch the ball.",
    "We looked forward to the school trip.",
    "The story moved forward to a new day.",
    "Please push the box forward a little.",
    "Think forward before you choose.",
    "The boat went forward in the calm water.",
    "Move forward one step at a time.",
    "The coach told us to move forward in a straight line.",
    "We walked forward across the hall.",
    "Ben leaned forward to tie his shoelace.",
    "Please step forward when your name is called.",
    "The story moved forward to the next day.",
    "Our boat went forward on the calm water.",
    "The class edged forward to see the map.",
    "Keep looking forward while you run.",
    "The line of pupils moved forward slowly."
  ],
  forwards: [
    "The class walked forwards in a neat line.",
    "Please move the chair forwards a little.",
    "She stepped forwards to read her poem.",
    "The bus rolled forwards at the stop.",
    "Tom pushed the tray forwards on the table.",
    "We edged forwards to see the stage.",
    "The duck waddled forwards to the pond.",
    "Keep your hands forwards when you catch the ball.",
    "The car moved forwards slowly.",
    "He leant forwards to tie his shoe.",
    "Move forwards one step at a time.",
    "The coach told us to move forwards in a straight line.",
    "We walked forwards across the hall.",
    "Ben leaned forwards to tie his shoelace.",
    "Please step forwards when your name is called.",
    "The story moved forwards to the next day.",
    "Our boat went forwards on the calm water.",
    "The class edged forwards to see the map.",
    "Keep looking forwards while you run.",
    "The line of pupils moved forwards slowly."
  ],
  fruit: [
    "Apples are a healthy fruit for lunch.",
    "The bowl of fruit looked bright and fresh.",
    "We added fruit to our cereal.",
    "Mango is my favourite fruit.",
    "The market sold ripe fruit from local farms.",
    "She packed fruit in her school bag.",
    "The smoothie had banana and fruit in it.",
    "Every child chose a piece of fruit.",
    "We cut up fruit for the picnic.",
    "The tree gave us one sweet fruit.",
    "The teacher wrote the word fruit on the board.",
    "We saw the word fruit on a flashcard.",
    "I heard the word fruit in the dictation.",
    "Our group used the word fruit in a story.",
    "Please spell the word fruit carefully.",
    "Sam said the word fruit aloud to the class.",
    "We checked the spelling of fruit against the answer sheet.",
    "The quiz included the word fruit as a challenge.",
    "I remembered the word fruit after more practice.",
    "The card showed the word fruit in bold."
  ],
  grammar: [
    "We practised grammar in English class.",
    "The teacher explained grammar with clear examples.",
    "Good grammar helps readers understand writing.",
    "Our test included grammar and spelling.",
    "He checked the grammar in his story.",
    "The class learned a new grammar rule.",
    "Poor grammar can make a sentence confusing.",
    "We talked about grammar before writing a letter.",
    "The book has a section on grammar.",
    "She used correct grammar in her answer.",
    "The teacher wrote the word grammar on the board.",
    "We saw the word grammar on a flashcard.",
    "I heard the word grammar in the dictation.",
    "Our group used the word grammar in a story.",
    "Please spell the word grammar carefully.",
    "Sam said the word grammar aloud to the class.",
    "We checked the spelling of grammar against the answer sheet.",
    "The quiz included the word grammar as a challenge.",
    "I remembered the word grammar after more practice.",
    "The card showed the word grammar in bold."
  ],
  group: [
    "Our group worked quietly at the table.",
    "The group shared the art supplies.",
    "Each group presented a different idea.",
    "I joined a reading group after school.",
    "The group walked to the hall together.",
    "We asked one group to tidy the books.",
    "A small group waited by the gate.",
    "The group chose a name for the project.",
    "The class split into a study group.",
    "Every group finished the task on time.",
    "The teacher wrote the word group on the board.",
    "We saw the word group on a flashcard.",
    "I heard the word group in the dictation.",
    "The class used the word group in a project.",
    "Please spell the word group carefully.",
    "Sam said the word group aloud to the class.",
    "We checked the spelling of group against the answer sheet.",
    "The quiz included the word group as a challenge.",
    "I remembered the word group after more practice.",
    "The card showed the word group in bold."
  ],
  guard: [
    "The guard stood by the gate.",
    "A guard checked the entrance to the museum.",
    "We saw a guard outside the castle.",
    "The guard opened the door for visitors.",
    "The guard wore a bright coat.",
    "A night guard kept watch in the car park.",
    "The guard smiled at the children.",
    "The guard asked us to stay behind the line.",
    "The castle guard told a short story.",
    "One guard helped us find the exit.",
    "The teacher wrote the word guard on the board.",
    "We saw the word guard on a flashcard.",
    "I heard the word guard in the dictation.",
    "Our group used the word guard in a story.",
    "Please spell the word guard carefully.",
    "Sam said the word guard aloud to the class.",
    "We checked the spelling of guard against the answer sheet.",
    "The quiz included the word guard as a challenge.",
    "I remembered the word guard after more practice.",
    "The card showed the word guard in bold."
  ],
  guide: [
    "Our guide showed us the old church.",
    "The guide led the class through the gallery.",
    "A guide explained the rules at the zoo.",
    "We followed the guide across the bridge.",
    "The guide pointed to the mountain peak.",
    "She used a guide to plan the walk.",
    "The guide spoke clearly and kindly.",
    "Our guide told us where to meet.",
    "A guide helped the visitors understand the map.",
    "The guide answered our questions after lunch.",
    "The teacher wrote the word guide on the board.",
    "We saw the word guide on a flashcard.",
    "I heard the word guide in the dictation.",
    "Our group used the word guide in a story.",
    "Please spell the word guide carefully.",
    "Sam said the word guide aloud to the class.",
    "We checked the spelling of guide against the answer sheet.",
    "The quiz included the word guide as a challenge.",
    "I remembered the word guide after more practice.",
    "The card showed the word guide in bold."
  ],
  heard: [
    "I heard the bell from my classroom.",
    "We heard music in the hall.",
    "Mum heard a noise outside the house.",
    "The class heard the teacher's instructions.",
    "Ben heard his name called from the field.",
    "I heard a funny story at break time.",
    "They heard thunder before the rain started.",
    "She heard the birds singing at dawn.",
    "We heard the news on the radio.",
    "Tom heard a splash near the pond.",
    "The teacher wrote the word heard on the board.",
    "We saw the word heard on a flashcard.",
    "The pupils used the word heard in a quiz.",
    "Our group used the word heard in a story.",
    "Please spell the word heard carefully.",
    "Sam said the word heard aloud to the class.",
    "We checked the spelling of heard against the answer sheet.",
    "The quiz included the word heard as a challenge.",
    "I remembered the word heard after more practice.",
    "The card showed the word heard in bold."
  ],
  heart: [
    "The heart pumps blood around the body.",
    "Her heart beat faster before the race.",
    "We drew a red heart on the card.",
    "A healthy heart needs exercise.",
    "He felt his heart thump with excitement.",
    "The doctor explained how the heart works.",
    "I made a paper heart for Mum.",
    "The story touched my heart.",
    "A strong heart helps us stay active.",
    "She wore a necklace with a heart charm.",
    "The teacher wrote the word heart on the board.",
    "We saw the word heart on a flashcard.",
    "I heard the word heart in the dictation.",
    "Our group used the word heart in a story.",
    "Please spell the word heart carefully.",
    "Sam said the word heart aloud to the class.",
    "We checked the spelling of heart against the answer sheet.",
    "The quiz included the word heart as a challenge.",
    "I remembered the word heart after more practice.",
    "The card showed the word heart in bold."
  ],
  height: [
    "The height of the tree surprised us.",
    "We measured the height of the box.",
    "His height made it easy to reach the shelf.",
    "The teacher wrote the height on the board.",
    "The height of the hill made us breathe hard.",
    "Please check the height before you jump.",
    "The height of the curtain was just right.",
    "Her height changed a lot this year.",
    "We compared the height of the two towers.",
    "The height of the fence kept the ball in.",
    "The teacher wrote the word height on the board.",
    "We saw the word height on a flashcard.",
    "I heard the word height in the dictation.",
    "Our group used the word height in a story.",
    "Please spell the word height carefully.",
    "Sam said the word height aloud to the class.",
    "We checked the spelling of height against the answer sheet.",
    "The quiz included the word height as a challenge.",
    "I remembered the word height after more practice.",
    "The card showed the word height in bold."
  ],
  history: [
    "We learn history on Fridays.",
    "The lesson on history was interesting.",
    "Our school museum has local history.",
    "She wrote a report about history.",
    "The castle has a long history.",
    "The class watched a film about history.",
    "I enjoy history because it tells stories.",
    "The book covers Roman history.",
    "We studied history in the library.",
    "The town's history is shown in the old photos.",
    "The teacher wrote the word history on the board.",
    "We saw the word history on a flashcard.",
    "I heard the word history in the dictation.",
    "Our group used the word history in a story.",
    "Please spell the word history carefully.",
    "Sam said the word history aloud to the class.",
    "We checked the spelling of history against the answer sheet.",
    "The quiz included the word history as a challenge.",
    "I remembered the word history after more practice.",
    "The card showed the word history in bold."
  ],
  imagine: [
    "Imagine a castle made of ice.",
    "Can you imagine living on a farm?",
    "I imagine the trip will be fun.",
    "Imagine a dog with bright blue spots.",
    "We can imagine the answer before we check.",
    "Try to imagine the view from the hill.",
    "I imagine the pond is deep.",
    "Imagine your own story ending.",
    "Can you imagine a world without books?",
    "We imagine a busy market at lunchtime.",
    "The teacher wrote the word imagine on the board.",
    "We saw the word imagine on a flashcard.",
    "I heard the word imagine in the dictation.",
    "Our group used the word imagine in a story.",
    "Please spell the word imagine carefully.",
    "Sam said the word imagine aloud to the class.",
    "We checked the spelling of imagine against the answer sheet.",
    "The quiz included the word imagine as a challenge.",
    "I remembered the word imagine after more practice.",
    "The card showed the word imagine in bold."
  ],
  increase: [
    "We saw an increase in bird numbers.",
    "The price may increase next month.",
    "Please increase the volume a little.",
    "The class recorded an increase in scores.",
    "An increase in rain made the path muddy.",
    "We hope to increase our reading time.",
    "The school plans to increase the number of clubs.",
    "A small increase can still help.",
    "The coach wants to increase our stamina.",
    "Scientists noticed an increase in daylight.",
    "The teacher wrote the word increase on the board.",
    "We saw the word increase on a flashcard.",
    "I heard the word increase in the dictation.",
    "Our group used the word increase in a story.",
    "Please spell the word increase carefully.",
    "Sam said the word increase aloud to the class.",
    "We checked the spelling of increase against the answer sheet.",
    "The quiz included the word increase as a challenge.",
    "I remembered the word increase after more practice.",
    "The card showed the word increase in bold."
  ],
  important: [
    "It is important to wear a helmet.",
    "Reading is important for every child.",
    "The teacher said water is important on hot days.",
    "It is important to listen carefully.",
    "The notice was important for the trip.",
    "Family time is important to me.",
    "The instructions are important for safety.",
    "It is important to finish your work.",
    "Sleep is important before a busy day.",
    "The sign gives an important message.",
    "The teacher wrote the word important on the board.",
    "We saw the word important on a flashcard.",
    "I heard the word important in the dictation.",
    "Our group used the word important in a story.",
    "Please spell the word important carefully.",
    "Sam said the word important aloud to the class.",
    "We checked the spelling of important against the answer sheet.",
    "The quiz included the word important as a challenge.",
    "I remembered the word important after more practice.",
    "The card showed the word important in bold."
  ],
  interest: [
    "The book caught my interest at once.",
    "I have a strong interest in science.",
    "The lesson was full of interest.",
    "Her interest in birds grew over time.",
    "The museum display held our interest.",
    "He showed interest in the football club.",
    "My interest in maps started last year.",
    "The class shared interest in space.",
    "Her interest in music is growing.",
    "We watched the show with interest.",
    "The teacher wrote the word interest on the board.",
    "We saw the word interest on a flashcard.",
    "I heard the word interest in the dictation.",
    "Our group used the word interest in a story.",
    "Please spell the word interest carefully.",
    "Sam said the word interest aloud to the class.",
    "We checked the spelling of interest against the answer sheet.",
    "The quiz included the word interest as a challenge.",
    "I remembered the word interest after more practice.",
    "The card showed the word interest in bold."
  ],
  island: [
    "We saw an island in the distance.",
    "The island has sandy beaches.",
    "Our map showed a small island.",
    "We sailed to the island at dawn.",
    "The island was quiet and green.",
    "Birds nested on the island.",
    "The island had one narrow road.",
    "We read about an island adventure.",
    "Fishermen lived near the island.",
    "The island shop sold postcards.",
    "The teacher wrote the word island on the board.",
    "We saw the word island on a flashcard.",
    "I heard the word island in the dictation.",
    "Our group used the word island in a story.",
    "Please spell the word island carefully.",
    "Sam said the word island aloud to the class.",
    "We checked the spelling of island against the answer sheet.",
    "The quiz included the word island as a challenge.",
    "I remembered the word island after more practice.",
    "The card showed the word island in bold."
  ],
  knowledge: [
    "Knowledge helps us solve problems.",
    "The lesson added to my knowledge.",
    "We shared knowledge about plants.",
    "Her knowledge of animals is strong.",
    "Good knowledge comes from reading.",
    "The quiz tested our knowledge.",
    "He used his knowledge to fix the bike.",
    "Our knowledge grew after the trip.",
    "The teacher valued every bit of knowledge.",
    "Knowledge of the area helped us walk home.",
    "The teacher wrote the word knowledge on the board.",
    "We saw the word knowledge on a flashcard.",
    "I heard the word knowledge in the dictation.",
    "Our group used the word knowledge in a story.",
    "Please spell the word knowledge carefully.",
    "Sam said the word knowledge aloud to the class.",
    "We checked the spelling of knowledge against the answer sheet.",
    "The quiz included the word knowledge as a challenge.",
    "I remembered the word knowledge after more practice.",
    "The card showed the word knowledge in bold."
  ],
  learn: [
    "We learn new words every week.",
    "I learn best with pictures.",
    "The class will learn about rivers.",
    "Children learn from reading aloud.",
    "We learn how to stay safe online.",
    "She wanted to learn a song.",
    "I learn by asking questions.",
    "The group can learn together.",
    "We learn from our mistakes.",
    "He hopes to learn chess soon.",
    "The teacher wrote the word learn on the board.",
    "We saw the word learn on a flashcard.",
    "I heard the word learn in the dictation.",
    "Our group used the word learn in a story.",
    "Please spell the word learn carefully.",
    "Sam said the word learn aloud to the class.",
    "We checked the spelling of learn against the answer sheet.",
    "The quiz included the word learn as a challenge.",
    "I remembered the word learn after more practice.",
    "The card showed the word learn in bold."
  ],
  length: [
    "Measure the length of the ribbon.",
    "The length of the table is two metres.",
    "We compared the length of both ropes.",
    "The teacher asked for the length of the line.",
    "The length of the journey was tiring.",
    "Please write the length in centimetres.",
    "The length of the hall surprised us.",
    "We checked the length before cutting the paper.",
    "The length of the scarf was just right.",
    "The length of the wall made decorating slow.",
    "The teacher wrote the word length on the board.",
    "We saw the word length on a flashcard.",
    "I heard the word length in the dictation.",
    "Our group used the word length in a story.",
    "Please spell the word length carefully.",
    "Sam said the word length aloud to the class.",
    "We checked the spelling of length against the answer sheet.",
    "The quiz included the word length as a challenge.",
    "I remembered the word length after more practice.",
    "The card showed the word length in bold."
  ],
  library: [
    "The library was quiet after lunch.",
    "We borrowed books from the library.",
    "Our class visited the library on Monday.",
    "The library has a new reading corner.",
    "She returned her book to the library.",
    "The library closed early on Friday.",
    "We found the atlas in the library.",
    "The library display showed local authors.",
    "I enjoy the library because it is calm.",
    "The library shelf held many stories.",
    "The teacher wrote the word library on the board.",
    "We saw the word library on a flashcard.",
    "I heard the word library in the dictation.",
    "Our group used the word library in a story.",
    "Please spell the word library carefully.",
    "Sam said the word library aloud to the class.",
    "We checked the spelling of library against the answer sheet.",
    "The quiz included the word library as a challenge.",
    "I remembered the word library after more practice.",
    "The card showed the word library in bold."
  ],
  material: [
    "This material feels soft and warm.",
    "The dress is made from a light material.",
    "We chose a strong material for the model.",
    "The roof material keeps out rain.",
    "The artist used a shiny material.",
    "The material on the table is waterproof.",
    "We sorted each material into a box.",
    "Cotton is a natural material.",
    "The teacher showed us a new material.",
    "The kite needs a thin material.",
    "The teacher wrote the word material on the board.",
    "We saw the word material on a flashcard.",
    "I heard the word material in the dictation.",
    "Our group used the word material in a story.",
    "Please spell the word material carefully.",
    "Sam said the word material aloud to the class.",
    "We checked the spelling of material against the answer sheet.",
    "The quiz included the word material as a challenge.",
    "I remembered the word material after more practice.",
    "The card showed the word material in bold."
  ],
  medicine: [
    "The doctor gave me medicine for my cough.",
    "Keep the medicine in a safe place.",
    "Mum measured the medicine carefully.",
    "The medicine tasted bitter.",
    "A nurse brought the medicine to the ward.",
    "We read the label on the medicine.",
    "The medicine helped him feel better.",
    "The shelf held every medicine in order.",
    "You must take the medicine after food.",
    "The medicine came with clear instructions.",
    "The teacher wrote the word medicine on the board.",
    "We saw the word medicine on a flashcard.",
    "I heard the word medicine in the dictation.",
    "Our group used the word medicine in a story.",
    "Please spell the word medicine carefully.",
    "Sam said the word medicine aloud to the class.",
    "We checked the spelling of medicine against the answer sheet.",
    "The quiz included the word medicine as a challenge.",
    "I remembered the word medicine after more practice.",
    "The card showed the word medicine in bold."
  ],
  mention: [
    "Please mention your answer in the letter.",
    "I did not mention the problem at first.",
    "The teacher will mention the trip tomorrow.",
    "Can you mention my name to the group?",
    "The report did not mention the rain.",
    "She wanted to mention the new club.",
    "He forgot to mention the homework.",
    "We may mention the book in class.",
    "The note did mention the meeting time.",
    "I should mention the change now.",
    "The teacher wrote the word mention on the board.",
    "We saw the word mention on a flashcard.",
    "I heard the word mention in the dictation.",
    "Our group used the word mention in a story.",
    "Please spell the word mention carefully.",
    "Sam said the word mention aloud to the class.",
    "We checked the spelling of mention against the answer sheet.",
    "The quiz included the word mention as a challenge.",
    "I remembered the word mention after more practice.",
    "The card showed the word mention in bold."
  ],
  minute: [
    "Wait one minute before you open it.",
    "The clock ticked every minute.",
    "We took a minute to think.",
    "The minute hand moved slowly.",
    "She was late by a minute.",
    "The task took only a minute.",
    "In a minute, the bell will ring.",
    "He checked the time every minute.",
    "The minute we arrived, it started to rain.",
    "Please stay for one more minute.",
    "The teacher wrote the word minute on the board.",
    "We saw the word minute on a flashcard.",
    "I heard the word minute in the dictation.",
    "Our group used the word minute in a story.",
    "Please spell the word minute carefully.",
    "Sam said the word minute aloud to the class.",
    "We checked the spelling of minute against the answer sheet.",
    "The quiz included the word minute as a challenge.",
    "I remembered the word minute after more practice.",
    "The card showed the word minute in bold."
  ],
  natural: [
    "Fresh air feels natural.",
    "The leaves had a natural green colour.",
    "It is natural to ask questions.",
    "The path looked natural in the wood.",
    "Her smile looked natural in the photo.",
    "We used natural light near the window.",
    "The river followed a natural route.",
    "He chose a natural voice for the play.",
    "The field looked natural after the rain.",
    "We talked about natural changes in the seasons.",
    "The teacher wrote the word natural on the board.",
    "We saw the word natural on a flashcard.",
    "I heard the word natural in the dictation.",
    "Our group used the word natural in a story.",
    "Please spell the word natural carefully.",
    "Sam said the word natural aloud to the class.",
    "We checked the spelling of natural against the answer sheet.",
    "The quiz included the word natural as a challenge.",
    "I remembered the word natural after more practice.",
    "The card showed the word natural in bold."
  ],
  naughty: [
    "The naughty puppy hid my shoe.",
    "A naughty child wrote on the desk.",
    "The naughty cat jumped on the counter.",
    "He gave a naughty grin.",
    "The naughty wind blew my hat away.",
    "The naughty class giggled during assembly.",
    "Our naughty dog dug in the garden.",
    "She played a naughty prank at lunch.",
    "The naughty rabbit escaped from the pen.",
    "The naughty boy hid behind the door.",
    "The teacher wrote the word naughty on the board.",
    "We saw the word naughty on a flashcard.",
    "I heard the word naughty in the dictation.",
    "Our group used the word naughty in a story.",
    "Please spell the word naughty carefully.",
    "Sam said the word naughty aloud to the class.",
    "We checked the spelling of naughty against the answer sheet.",
    "The quiz included the word naughty as a challenge.",
    "I remembered the word naughty after more practice.",
    "The card showed the word naughty in bold."
  ],
  notice: [
    "I notice the clock on the wall.",
    "We notice the signs by the path.",
    "The teacher asked us to notice the details.",
    "Please notice the change in colour.",
    "She did not notice the missing pen.",
    "I notice a star in the sky.",
    "They notice the quiet room at once.",
    "We notice how the leaves move.",
    "He will notice the new display.",
    "I always notice the smell of fresh bread.",
    "The teacher wrote the word notice on the board.",
    "We saw the word notice on a flashcard.",
    "I heard the word notice in the dictation.",
    "Our group used the word notice in a story.",
    "Please spell the word notice carefully.",
    "Sam said the word notice aloud to the class.",
    "We checked the spelling of notice against the answer sheet.",
    "The quiz included the word notice as a challenge.",
    "I remembered the word notice after more practice.",
    "The card showed the word notice in bold."
  ],
  occasion: [
    "The picnic was a happy occasion.",
    "Birthdays are a special occasion.",
    "We wore smart clothes for the occasion.",
    "The ceremony was a proud occasion.",
    "A school concert is a great occasion.",
    "On this occasion, the team won.",
    "The occasion called for a speech.",
    "It was a rare occasion to see snow.",
    "The cake was made for the occasion.",
    "She smiled at the occasion.",
    "The teacher wrote the word occasion on the board.",
    "We saw the word occasion on a flashcard.",
    "I heard the word occasion in the dictation.",
    "Our group used the word occasion in a story.",
    "Please spell the word occasion carefully.",
    "Sam said the word occasion aloud to the class.",
    "We checked the spelling of occasion against the answer sheet.",
    "The quiz included the word occasion as a challenge.",
    "I remembered the word occasion after more practice.",
    "The card showed the word occasion in bold."
  ],
  occasionally: [
    "We occasionally visit the seaside.",
    "She occasionally reads in the garden.",
    "I occasionally forget my water bottle.",
    "We occasionally hear owls at night.",
    "Dad occasionally cooks pasta on Fridays.",
    "The bus is occasionally late.",
    "They occasionally play chess after school.",
    "I occasionally help at the library.",
    "We occasionally watch a film together.",
    "He occasionally carries the class books.",
    "We occasionally take the long route home.",
    "I occasionally help Mum water the plants.",
    "The class occasionally visits the local museum.",
    "Dad occasionally reads a story after tea.",
    "We occasionally hear foxes in the park.",
    "She occasionally writes postcards to her cousin.",
    "Our team occasionally practises in the sports hall.",
    "I occasionally save a seat for my friend.",
    "The teacher occasionally changes the order of the tasks.",
    "We occasionally bake cakes at the weekend."
  ],
  often: [
    "We often walk to school.",
    "She often reads before bed.",
    "I often spot deer near the woods.",
    "I often see rabbits in the field.",
    "Dad often makes tea after work.",
    "We often visit the park.",
    "The dog often sits by the door.",
    "I often need a second look.",
    "They often play outside at break time.",
    "Our teacher often asks for quiet.",
    "We often walk to school together.",
    "I often read before bed.",
    "The class often practises spellings.",
    "Mum often packs fruit for lunch.",
    "We often visit the park at weekends.",
    "The dog often waits by the door.",
    "I often hear birds in the morning.",
    "Our teacher often asks us to explain our answers.",
    "Ben often helps his little sister.",
    "We often use the library after school."
  ],
  opposite: [
    "The shop is opposite the post office.",
    "We sat opposite the stage.",
    "Her desk is opposite mine.",
    "The car stopped opposite the gate.",
    "I walked opposite the cafe.",
    "The mirror is opposite the window.",
    "They live opposite the school.",
    "The path runs opposite the river.",
    "Our seats were opposite each other.",
    "The tower stands opposite the library.",
    "The teacher wrote the word opposite on the board.",
    "We saw the word opposite on a flashcard.",
    "I heard the word opposite in the dictation.",
    "Our group used the word opposite in a story.",
    "Please spell the word opposite carefully.",
    "Sam said the word opposite aloud to the class.",
    "We checked the spelling of opposite against the answer sheet.",
    "The quiz included the word opposite as a challenge.",
    "I remembered the word opposite after more practice.",
    "The card showed the word opposite in bold."
  ]
});
