window.KS2_SENTENCE_BANK = Object.assign(window.KS2_SENTENCE_BANK || {}, {
  ordinary: [
    "It was an ordinary day at school.",
    "We ate an ordinary lunch in the hall.",
    "The box looked ordinary, but it held a prize.",
    "She wore an ordinary coat to stay warm.",
    "The story began in an ordinary village.",
    "He chose an ordinary pencil for the test.",
    "Our class had an ordinary assembly on Monday.",
    "They sat at an ordinary wooden table.",
    "The room seemed ordinary until the lights changed.",
    "He liked ordinary tasks because they were calm.",
    "We practised the word ordinary with a partner.",
    "The teacher put ordinary on the board.",
    "I copied ordinary into my spelling book.",
    "Our class used ordinary in a quick quiz.",
    "At home, I practised ordinary before tea.",
    "The spelling card helped me remember ordinary.",
    "We checked ordinary after lunch.",
    "A friend asked me to spell ordinary again.",
    "I saw ordinary on the revision sheet.",
    "By the end of the lesson, I could spell ordinary without help."
  ],
  particular: [
    "She had a particular way of tying her shoes.",
    "We need a particular size for the box.",
    "He chose a particular book from the shelf.",
    "The teacher had a particular rule for tidy work.",
    "I remember one particular day very well.",
    "They wanted a particular shade of blue.",
    "Mum asked for a particular answer.",
    "The dog likes one particular ball.",
    "There was a particular smell in the kitchen.",
    "She made a particular effort to help.",
    "We practised the word particular with a partner.",
    "The teacher put particular on the board.",
    "I copied particular into my spelling book.",
    "Our class used particular in a quick quiz.",
    "At home, I practised particular before tea.",
    "The spelling card helped me remember particular.",
    "We checked particular after lunch.",
    "A friend asked me to spell particular again.",
    "I saw particular on the revision sheet.",
    "By the end of the lesson, I could spell particular without help."
  ],
  peculiar: [
    "The old house had a peculiar sound at night.",
    "He wore a peculiar hat to the party.",
    "The cake had a peculiar taste.",
    "She noticed a peculiar mark on the wall.",
    "It felt peculiar to walk in silence.",
    "The bird made a peculiar call.",
    "He gave a peculiar smile after the joke.",
    "We found a peculiar stone by the path.",
    "The room had a peculiar smell of paint.",
    "It was peculiar to see snow in April.",
    "We practised the word peculiar with a partner.",
    "The teacher put peculiar on the board.",
    "I copied peculiar into my spelling book.",
    "Our class used peculiar in a quick quiz.",
    "At home, I practised peculiar before tea.",
    "The spelling card helped me remember peculiar.",
    "We checked peculiar after lunch.",
    "A friend asked me to spell peculiar again.",
    "I saw peculiar on the revision sheet.",
    "By the end of the lesson, I could spell peculiar without help."
  ],
  perhaps: [
    "I think perhaps we should leave earlier.",
    "The train will perhaps be on time.",
    "She perhaps forgot her bag at home.",
    "I can perhaps help after lunch.",
    "The rain may perhaps stop soon.",
    "They perhaps chose the wrong path.",
    "You should perhaps ask the teacher.",
    "The answer may perhaps be under the book.",
    "We will perhaps visit the museum tomorrow.",
    "He perhaps meant to call later.",
    "We practised the word perhaps with a partner.",
    "The teacher put perhaps on the board.",
    "I copied perhaps into my spelling book.",
    "Our class used perhaps in a quick quiz.",
    "At home, I practised perhaps before tea.",
    "The spelling card helped me remember perhaps.",
    "We checked perhaps after lunch.",
    "A friend asked me to spell perhaps again.",
    "I saw perhaps on the revision sheet.",
    "By the end of the lesson, I could spell perhaps without help."
  ],
  popular: [
    "The park is a popular place to play.",
    "That song is popular with our class.",
    "Apples are a popular snack at break time.",
    "The new comic was very popular.",
    "The library is a popular spot after school.",
    "Football is a popular game in our town.",
    "Her ideas became popular quickly.",
    "The seaside town is popular in summer.",
    "That shoe style was popular last year.",
    "Hot chocolate is popular on cold days.",
    "We practised the word popular with a partner.",
    "The teacher put popular on the board.",
    "I copied popular into my spelling book.",
    "Our class used popular in a quick quiz.",
    "At home, I practised popular before tea.",
    "The spelling card helped me remember popular.",
    "We checked popular after lunch.",
    "A friend asked me to spell popular again.",
    "I saw popular on the revision sheet.",
    "By the end of the lesson, I could spell popular without help."
  ],
  position: [
    "She moved into position behind the rope.",
    "The coach changed his position on the team.",
    "Please hold your position in the line.",
    "He found a better position near the window.",
    "The map showed the position of the castle.",
    "We took our position for the photograph.",
    "The dancer kept her position with care.",
    "His position on the chair was uncomfortable.",
    "They studied the position of the stars.",
    "She moved the ladder into position.",
    "We practised the word position with a partner.",
    "The teacher put position on the board.",
    "I copied position into my spelling book.",
    "Our class used position in a quick quiz.",
    "At home, I practised position before tea.",
    "The spelling card helped me remember position.",
    "We checked position after lunch.",
    "A friend asked me to spell position again.",
    "I saw position on the revision sheet.",
    "By the end of the lesson, I could spell position without help."
  ],
  possess: [
    "Many people possess a good sense of humour.",
    "Some birds possess bright feathers.",
    "You must possess your library card to borrow books.",
    "A great player must possess skill and patience.",
    "The castle was said to possess secret tunnels.",
    "He does not possess a loud voice.",
    "We all possess different talents.",
    "The old map may possess clues.",
    "She seems to possess great confidence.",
    "Few trees possess such strong roots.",
    "We practised the word possess with a partner.",
    "The teacher put possess on the board.",
    "I copied possess into my spelling book.",
    "Our class used possess in a quick quiz.",
    "At home, I practised possess before tea.",
    "The spelling card helped me remember possess.",
    "We checked possess after lunch.",
    "A friend asked me to spell possess again.",
    "I saw possess on the revision sheet.",
    "By the end of the lesson, I could spell possess without help."
  ],
  possession: [
    "The necklace was in her possession.",
    "He kept his possession safe in a box.",
    "The shop returned the lost possession to the child.",
    "A football is his favourite possession.",
    "The bag was not in his possession.",
    "The painting was a precious possession.",
    "She kept the letter in her possession.",
    "The key was found in his possession.",
    "The old watch became a treasured possession.",
    "The medal became my grandad's treasured possession.",
    "We practised the word possession with a partner.",
    "The teacher put possession on the board.",
    "I copied possession into my spelling book.",
    "Our class used possession in a quick quiz.",
    "At home, I practised possession before tea.",
    "The spelling card helped me remember possession.",
    "We checked possession after lunch.",
    "A friend asked me to spell possession again.",
    "I saw possession on the revision sheet.",
    "By the end of the lesson, I could spell possession without help."
  ],
  possible: [
    "It is possible to finish before lunch.",
    "We walked as quietly as possible.",
    "Please give as much help as possible.",
    "It is possible that the bus is late.",
    "Try to make the picture as clear as possible.",
    "We used every possible clue.",
    "It is possible to learn from mistakes.",
    "She made the best possible choice.",
    "Keep the door open if possible.",
    "We looked for every possible route.",
    "We practised the word possible with a partner.",
    "The teacher put possible on the board.",
    "I copied possible into my spelling book.",
    "Our class used possible in a quick quiz.",
    "At home, I practised possible before tea.",
    "The spelling card helped me remember possible.",
    "We checked possible after lunch.",
    "A friend asked me to spell possible again.",
    "I saw possible on the revision sheet.",
    "By the end of the lesson, I could spell possible without help."
  ],
  potatoes: [
    "Mum boiled the potatoes for dinner.",
    "We planted potatoes in the school garden.",
    "The potatoes were soft and warm.",
    "He mashed the potatoes with butter.",
    "Roast potatoes smell delicious.",
    "The farmer loaded sacks of potatoes onto the cart.",
    "We ate potatoes with our pie.",
    "The potatoes grew well after the rain.",
    "She peeled the potatoes carefully.",
    "Chips are made from potatoes.",
    "We practised the word potatoes with a partner.",
    "The teacher put potatoes on the board.",
    "I copied potatoes into my spelling book.",
    "Our class used potatoes in a quick quiz.",
    "At home, I practised potatoes before tea.",
    "The spelling card helped me remember potatoes.",
    "We checked potatoes after lunch.",
    "A friend asked me to spell potatoes again.",
    "I saw potatoes on the revision sheet.",
    "By the end of the lesson, I could spell potatoes without help."
  ],
  pressure: [
    "The lid came off under pressure.",
    "She felt pressure before the test.",
    "The pipe burst because of pressure.",
    "He stayed calm under pressure.",
    "Too much pressure can break the glass.",
    "The team faced pressure to win.",
    "Air pressure changes with the weather.",
    "She handled the pressure well.",
    "Water pressure was low in the morning.",
    "He put pressure on the button.",
    "We practised the word pressure with a partner.",
    "The teacher put pressure on the board.",
    "I copied pressure into my spelling book.",
    "Our class used pressure in a quick quiz.",
    "At home, I practised pressure before tea.",
    "The spelling card helped me remember pressure.",
    "We checked pressure after lunch.",
    "A friend asked me to spell pressure again.",
    "I saw pressure on the revision sheet.",
    "By the end of the lesson, I could spell pressure without help."
  ],
  probably: [
    "We will probably leave after tea.",
    "It will probably rain later.",
    "She will probably join the game.",
    "The cat is probably under the table.",
    "He will probably read that book again.",
    "They are probably on the bus now.",
    "The work will probably take an hour.",
    "I will probably choose the blue pen.",
    "The dog is probably asleep upstairs.",
    "We should probably check the map.",
    "We practised the word probably with a partner.",
    "The teacher put probably on the board.",
    "I copied probably into my spelling book.",
    "Our class used probably in a quick quiz.",
    "At home, I practised probably before tea.",
    "The spelling card helped me remember probably.",
    "We checked probably after lunch.",
    "A friend asked me to spell probably again.",
    "I saw probably on the revision sheet.",
    "By the end of the lesson, I could spell probably without help."
  ],
  promise: [
    "I promise to be ready on time.",
    "She made a promise to help her brother.",
    "We promise to keep the gate shut.",
    "He broke his promise to call.",
    "My promise is to try my best.",
    "They promise to finish the job today.",
    "A promise should be kept.",
    "She gave her promise in writing.",
    "I promise to listen carefully.",
    "His promise cheered the whole class.",
    "We practised the word promise with a partner.",
    "The teacher put promise on the board.",
    "I copied promise into my spelling book.",
    "Our class used promise in a quick quiz.",
    "At home, I practised promise before tea.",
    "The spelling card helped me remember promise.",
    "We checked promise after lunch.",
    "A friend asked me to spell promise again.",
    "I saw promise on the revision sheet.",
    "By the end of the lesson, I could spell promise without help."
  ],
  purpose: [
    "The purpose of the sign was clear.",
    "She packed the bag for a purpose.",
    "Our purpose today is to learn.",
    "He acted with purpose and confidence.",
    "The ladder had no purpose in the room.",
    "We made the trip with a purpose.",
    "The game had a purpose in the lesson.",
    "Her purpose was to help her friend.",
    "He worked with purpose all morning.",
    "The key was kept for a purpose.",
    "We practised the word purpose with a partner.",
    "The teacher put purpose on the board.",
    "I copied purpose into my spelling book.",
    "Our class used purpose in a quick quiz.",
    "At home, I practised purpose before tea.",
    "The spelling card helped me remember purpose.",
    "We checked purpose after lunch.",
    "A friend asked me to spell purpose again.",
    "I saw purpose on the revision sheet.",
    "By the end of the lesson, I could spell purpose without help."
  ],
  quarter: [
    "We walked a quarter of the way home.",
    "The cake was cut into a quarter.",
    "It is a quarter past three.",
    "The shop is a quarter mile away.",
    "She found a quarter of the answer.",
    "A quarter of the class went swimming.",
    "He paid with a quarter from his pocket.",
    "The team scored in the first quarter.",
    "We waited for a quarter of an hour.",
    "The map showed one quarter of the town.",
    "We practised the word quarter with a partner.",
    "The teacher put quarter on the board.",
    "I copied quarter into my spelling book.",
    "Our class used quarter in a quick quiz.",
    "At home, I practised quarter before tea.",
    "The spelling card helped me remember quarter.",
    "We checked quarter after lunch.",
    "A friend asked me to spell quarter again.",
    "I saw quarter on the revision sheet.",
    "By the end of the lesson, I could spell quarter without help."
  ],
  question: [
    "I had a question about the homework.",
    "She raised her hand to question the rule.",
    "The question was harder than it looked.",
    "We asked a question at the end.",
    "His question helped the class think.",
    "The teacher answered every question.",
    "I wrote one question on my card.",
    "The next question was about history.",
    "They discussed the question after lunch.",
    "Your question made me look again.",
    "We practised the word question with a partner.",
    "The teacher put question on the board.",
    "I copied question into my spelling book.",
    "Our class used question in a quick quiz.",
    "At home, I practised question before tea.",
    "The spelling card helped me remember question.",
    "We checked question after lunch.",
    "A friend asked me to spell question again.",
    "I saw question on the revision sheet.",
    "By the end of the lesson, I could spell question without help."
  ],
  recent: [
    "We moved to a recent house.",
    "She read a recent book from the library.",
    "A recent storm damaged the fence.",
    "His recent work was very neat.",
    "We saw her recent painting on the wall.",
    "The recent rain filled the pond.",
    "A recent message arrived on my phone.",
    "The class studied recent events.",
    "My recent trip was full of fun.",
    "The recent news surprised everyone.",
    "We practised the word recent with a partner.",
    "The teacher put recent on the board.",
    "I copied recent into my spelling book.",
    "Our class used recent in a quick quiz.",
    "At home, I practised recent before tea.",
    "The spelling card helped me remember recent.",
    "We checked recent after lunch.",
    "A friend asked me to spell recent again.",
    "I saw recent on the revision sheet.",
    "By the end of the lesson, I could spell recent without help."
  ],
  regular: [
    "She has a regular routine before school.",
    "We make regular visits to the library.",
    "He is a regular visitor to the park.",
    "The bus makes a regular stop here.",
    "They had regular practice on Fridays.",
    "A regular shape has clear sides.",
    "Mum checks the dog on a regular basis.",
    "We eat at regular times each day.",
    "The teacher liked the regular pattern.",
    "He kept a regular pace on the hill.",
    "We practised the word regular with a partner.",
    "The teacher put regular on the board.",
    "I copied regular into my spelling book.",
    "Our class used regular in a quick quiz.",
    "At home, I practised regular before tea.",
    "The spelling card helped me remember regular.",
    "We checked regular after lunch.",
    "A friend asked me to spell regular again.",
    "I saw regular on the revision sheet.",
    "By the end of the lesson, I could spell regular without help."
  ],
  reign: [
    "The king's reign lasted many years.",
    "Her reign as captain was successful.",
    "A long reign can change a country.",
    "The queen's reign ended in peace.",
    "The idea had a brief reign in class.",
    "The royal reign was marked by festivals.",
    "His reign brought new laws.",
    "During the reign of the queen, art grew.",
    "The reign of the old king was remembered.",
    "Peace returned after the reign ended.",
    "We practised the word reign with a partner.",
    "The teacher put reign on the board.",
    "I copied reign into my spelling book.",
    "Our class used reign in a quick quiz.",
    "At home, I practised reign before tea.",
    "The spelling card helped me remember reign.",
    "We checked reign after lunch.",
    "A friend asked me to spell reign again.",
    "I saw reign on the revision sheet.",
    "By the end of the lesson, I could spell reign without help."
  ],
  remember: [
    "Please remember your coat.",
    "I remember the trip clearly.",
    "She will remember his kind words.",
    "We remember to feed the rabbit.",
    "He did not remember the answer.",
    "I remember where I left my bag.",
    "Please remember to close the door.",
    "They remember that story every winter.",
    "She will remember her first day at school.",
    "We remember to check our work.",
    "We practised the word remember with a partner.",
    "The teacher put remember on the board.",
    "I copied remember into my spelling book.",
    "Our class used remember in a quick quiz.",
    "At home, I practised remember before tea.",
    "The spelling card helped me remember the answer.",
    "We checked remember after lunch.",
    "A friend asked me to spell remember again.",
    "I saw remember on the revision sheet.",
    "By the end of the lesson, I could spell remember without help."
  ],
  sentence: [
    "Write a clear sentence for the test.",
    "The teacher asked for one sentence.",
    "He said the sentence aloud.",
    "Please copy the sentence neatly.",
    "She joined two ideas in one sentence.",
    "The sentence was long but simple.",
    "I underlined the key sentence.",
    "We built a sentence together.",
    "The last sentence made everyone smile.",
    "Can you say that sentence again.",
    "We practised the word sentence with a partner.",
    "The teacher put sentence on the board.",
    "I copied sentence into my spelling book.",
    "Our class used sentence in a quick quiz.",
    "At home, I practised sentence before tea.",
    "The spelling card helped me remember sentence.",
    "We checked sentence after lunch.",
    "A friend asked me to spell sentence again.",
    "I saw sentence on the revision sheet.",
    "By the end of the lesson, I could spell sentence without help."
  ],
  separate: [
    "Please separate the red buttons from the blue ones.",
    "We need to separate the papers.",
    "The fence helps separate the fields.",
    "She had to separate the coins by size.",
    "Try to separate the eggs carefully.",
    "The river can separate the two villages.",
    "We separate our shoes from our coats.",
    "The teacher will separate the class into groups.",
    "The line helps separate the two lanes.",
    "It is hard to separate fact from guess.",
    "We practised the word separate with a partner.",
    "The teacher put separate on the board.",
    "I copied separate into my spelling book.",
    "Our class used separate in a quick quiz.",
    "At home, I practised separate before tea.",
    "The spelling card helped me remember separate.",
    "We checked separate after lunch.",
    "A friend asked me to spell separate again.",
    "I saw separate on the revision sheet.",
    "By the end of the lesson, I could spell separate without help."
  ],
  special: [
    "Today is a special day for our class.",
    "She wore a special badge on her coat.",
    "We made a special card for Mum.",
    "The cake had a special icing.",
    "He saved a special seat for his friend.",
    "The library put on a special display.",
    "That song has a special meaning for me.",
    "We used a special pen for the poster.",
    "The trip was special because we went together.",
    "Grandad told a special story at bedtime.",
    "We practised the word special with a partner.",
    "The teacher put special on the board.",
    "I copied special into my spelling book.",
    "Our class used special in a quick quiz.",
    "At home, I practised special before tea.",
    "The spelling card helped me remember special.",
    "We checked special after lunch.",
    "A friend asked me to spell special again.",
    "I saw special on the revision sheet.",
    "By the end of the lesson, I could spell special without help."
  ],
  straight: [
    "Draw a straight line across the page.",
    "He walked straight to the gate.",
    "The road ahead is straight and long.",
    "Please keep the shelves straight.",
    "She stood up straight for the photo.",
    "The arrow flew straight to the target.",
    "We took a straight path through the field.",
    "Put the books straight on the shelf.",
    "His hair was brushed straight.",
    "The ruler helped me make a straight edge.",
    "We practised the word straight with a partner.",
    "The teacher put straight on the board.",
    "I copied straight into my spelling book.",
    "Our class used straight in a quick quiz.",
    "At home, I practised straight before tea.",
    "The spelling card helped me remember straight.",
    "We checked straight after lunch.",
    "A friend asked me to spell straight again.",
    "I saw straight on the revision sheet.",
    "By the end of the lesson, I could spell straight without help."
  ],
  strange: [
    "That was a strange sound in the hall.",
    "She found a strange shell on the beach.",
    "It felt strange to be so quiet.",
    "The sky looked strange before the storm.",
    "He wore a strange hat to school.",
    "We noticed a strange smell in the room.",
    "The story had a strange ending.",
    "It is strange to see snow in spring.",
    "She gave me a strange look.",
    "The cat made a strange little noise.",
    "We practised the word strange with a partner.",
    "The teacher put strange on the board.",
    "I copied strange into my spelling book.",
    "Our class used strange in a quick quiz.",
    "At home, I practised strange before tea.",
    "The spelling card helped me remember strange.",
    "We checked strange after lunch.",
    "A friend asked me to spell strange again.",
    "I saw strange on the revision sheet.",
    "By the end of the lesson, I could spell strange without help."
  ],
  strength: [
    "Exercise can build your strength.",
    "She showed great strength in the race.",
    "The rope has enough strength to hold us.",
    "His strength helped the team win.",
    "We admired her strength and courage.",
    "The bridge needed more strength.",
    "Swimming can improve your strength.",
    "The wall has surprising strength.",
    "He used all his strength to lift the box.",
    "Kindness is a quiet strength.",
    "We practised the word strength with a partner.",
    "The teacher put strength on the board.",
    "I copied strength into my spelling book.",
    "Our class used strength in a quick quiz.",
    "At home, I practised strength before tea.",
    "The spelling card helped me remember strength.",
    "We checked strength after lunch.",
    "A friend asked me to spell strength again.",
    "I saw strength on the revision sheet.",
    "By the end of the lesson, I could spell strength without help."
  ],
  suppose: [
    "I suppose we could try a new route.",
    "I suppose the shop is closed now.",
    "I suppose the answer is wrong.",
    "I suppose we can ask for help.",
    "I suppose you will finish early.",
    "We can suppose that it will rain.",
    "I suppose the game starts at three.",
    "I suppose the dog needs water.",
    "I suppose your idea may work.",
    "I suppose we meet at the gate.",
    "We practised the word suppose with a partner.",
    "The teacher put suppose on the board.",
    "I copied suppose into my spelling book.",
    "Our class used suppose in a quick quiz.",
    "At home, I practised suppose before tea.",
    "The spelling card helped me remember suppose.",
    "We checked suppose after lunch.",
    "A friend asked me to spell suppose again.",
    "I saw suppose on the revision sheet.",
    "By the end of the lesson, I could spell suppose without help."
  ],
  surprise: [
    "The party was a surprise for her.",
    "We wanted to surprise Dad with a card.",
    "It was no surprise that she won.",
    "The box held a surprise gift.",
    "His visit was a surprise to everyone.",
    "She tried to surprise the class.",
    "The result came as a surprise.",
    "We planned a surprise for the teacher.",
    "The puppy was a happy surprise.",
    "Do not surprise the birds near the pond.",
    "We practised the word surprise with a partner.",
    "The teacher put surprise on the board.",
    "I copied surprise into my spelling book.",
    "Our class used surprise in a quick quiz.",
    "At home, I practised surprise before tea.",
    "The spelling card helped me remember surprise.",
    "We checked surprise after lunch.",
    "A friend asked me to spell surprise again.",
    "I saw surprise on the revision sheet.",
    "By the end of the lesson, I could spell surprise without help."
  ],
  therefore: [
    "It was cold, therefore we wore coats.",
    "He was late, therefore he ran.",
    "The road was wet, therefore we walked carefully.",
    "She studied well, therefore she did well.",
    "The match was cancelled, therefore we went home.",
    "The pencil broke, therefore I used a pen.",
    "The shop was shut, therefore we tried another one.",
    "He was ill, therefore he stayed indoors.",
    "The gate was locked, therefore we used the side door.",
    "The milk was sour, therefore we threw it away.",
    "We practised the word therefore with a partner.",
    "The teacher put therefore on the board.",
    "I copied therefore into my spelling book.",
    "Our class used therefore in a quick quiz.",
    "At home, I practised therefore before tea.",
    "The spelling card helped me remember therefore.",
    "We checked therefore after lunch.",
    "A friend asked me to spell therefore again.",
    "I saw therefore on the revision sheet.",
    "By the end of the lesson, I could spell therefore without help."
  ],
  though: [
    "We played outside, though it was cold.",
    "I liked the book, though it was long.",
    "She smiled, though she was tired.",
    "We kept going, though the path was muddy.",
    "He hurried, though he was late.",
    "The dog was brave, though small.",
    "We went out, though it rained a little.",
    "I tried my best, though the test was hard.",
    "We found the torch, though the room was dark.",
    "She agreed, though she had doubts.",
    "We practised the word though with a partner.",
    "The teacher put though on the board.",
    "I copied though into my spelling book.",
    "Our class used though in a quick quiz.",
    "At home, I practised though before tea.",
    "The spelling card helped me remember though.",
    "We checked though after lunch.",
    "A friend asked me to spell though again.",
    "I saw though on the revision sheet.",
    "By the end of the lesson, I could spell though without help."
  ],
  although: [
    "We went out although it was raining.",
    "She finished the page although she was tired.",
    "The cake tasted good although it looked plain.",
    "He was strong although he was small.",
    "The teacher was kind although we were late.",
    "We crossed safely although the road was busy.",
    "I answered the question although I was nervous.",
    "The dog was friendly although it barked.",
    "She kept going although the task was hard.",
    "We could still see although it was dark.",
    "We practised the word although with a partner.",
    "The teacher put although on the board.",
    "I copied although into my spelling book.",
    "Our class used although in a quick quiz.",
    "At home, I practised although before tea.",
    "The spelling card helped me remember although.",
    "We checked although after lunch.",
    "A friend asked me to spell although again.",
    "I saw although on the revision sheet.",
    "By the end of the lesson, I could spell although without help."
  ],
  thought: [
    "I thought the game was fun.",
    "She thought carefully before speaking.",
    "We thought the answer was easy.",
    "He thought about the problem all night.",
    "I thought I heard a bell.",
    "The class thought the joke was silly.",
    "She thought of a better plan.",
    "We thought the path led home.",
    "He thought the box was empty.",
    "I thought it would be sunny.",
    "We practised the word thought with a partner.",
    "The teacher put thought on the board.",
    "I copied thought into my spelling book.",
    "Our class used thought in a quick quiz.",
    "At home, I practised thought before tea.",
    "The spelling card helped me remember thought.",
    "We checked thought after lunch.",
    "A friend asked me to spell thought again.",
    "I saw thought on the revision sheet.",
    "By the end of the lesson, I could spell thought without help."
  ],
  through: [
    "We walked through the park.",
    "The light shone through the window.",
    "She read through the list.",
    "He pushed through the crowd.",
    "We looked through the glass.",
    "The river ran through the valley.",
    "She climbed through the opening.",
    "He went through the gate.",
    "The train passed through the tunnel.",
    "We worked through the puzzle.",
    "We practised the word through with a partner.",
    "The teacher put through on the board.",
    "I copied through into my spelling book.",
    "Our class used through in a quick quiz.",
    "At home, I practised through before tea.",
    "The spelling card helped me remember through.",
    "We checked through after lunch.",
    "A friend asked me to spell through again.",
    "I saw through on the revision sheet.",
    "By the end of the lesson, I could spell through without help."
  ],
  various: [
    "The box held various colours of beads.",
    "We tried various ways to solve it.",
    "She visited various towns on holiday.",
    "The class used various tools in art.",
    "There were various birds in the tree.",
    "He read various books about space.",
    "We tasted various apples at the fair.",
    "The shop sold various kinds of bread.",
    "She had various ideas for the poster.",
    "There were various signs pointing to the hall.",
    "We practised the word various with a partner.",
    "The teacher put various on the board.",
    "I copied various into my spelling book.",
    "Our class used various in a quick quiz.",
    "At home, I practised various before tea.",
    "The spelling card helped me remember various.",
    "We checked various after lunch.",
    "A friend asked me to spell various again.",
    "I saw various on the revision sheet.",
    "By the end of the lesson, I could spell various without help."
  ],
  weight: [
    "The weight of the bag made it hard to lift.",
    "She checked the weight before posting the parcel.",
    "The bridge can hold a lot of weight.",
    "He balanced the weight on both hands.",
    "The weight of the box surprised me.",
    "We cut the weight by removing the extra parts.",
    "The doctor asked for his weight.",
    "The weight of the snow bent the branch.",
    "She could feel the weight in her backpack.",
    "The scales showed the weight clearly.",
    "We practised the word weight with a partner.",
    "The teacher put weight on the board.",
    "I copied weight into my spelling book.",
    "Our class used weight in a quick quiz.",
    "At home, I practised weight before tea.",
    "The spelling card helped me remember weight.",
    "We checked weight after lunch.",
    "A friend asked me to spell weight again.",
    "I saw weight on the revision sheet.",
    "By the end of the lesson, I could spell weight without help."
  ],
  woman: [
    "The woman in the red coat waved.",
    "A woman came to read with us.",
    "The woman at the desk helped me.",
    "My aunt is a kind woman.",
    "One woman led the line through the hall.",
    "The woman beside the gate smiled.",
    "A young woman ran the stall.",
    "The woman on the bus gave up her seat.",
    "The woman carried the cake carefully.",
    "The woman taught us a song.",
    "We practised the word woman with a partner.",
    "The teacher put woman on the board.",
    "I copied woman into my spelling book.",
    "Our class used woman in a quick quiz.",
    "At home, I practised woman before tea.",
    "The spelling card helped me remember woman.",
    "We checked woman after lunch.",
    "A friend asked me to spell woman again.",
    "I saw woman on the revision sheet.",
    "By the end of the lesson, I could spell woman without help."
  ]
});
